server:
  port: 8081
spring:
  application:
    name: storage-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata-demo?characterEncoding=utf8?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 106.14.184.129:8848
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: not_null
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.cloud.alibaba.seata.web: debug
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 106.14.184.129:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
      cluster: SH
  tx-service-group: seata-demo
#  service:
#    vgroup-mapping:
#      seata-demo: SH
  data-source-proxy-mode: AT
  config:
    type: nacos
    nacos:
      server-addr: 106.14.184.129:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP
      data-id: client.properties